### ISSUE TITLE
Original pre-requisites needed? Running of this Remastersys?

### ISSUE THREAD

**Issue by MarioCavero** [Nerun/remastersys#1]
Thanks for your work!

Before using this repo, is it necessary to do the steps informed in the [original Remastersys website](https://web.archive.org/web/20130423105647/http://www.remastersys.com/)? For example, for a Debian system:

> There are some pre-requisites for the debian version that aren't there for the Ubuntu version.
> 
>   You should install squashfs-modules for your kernel and either aufs-modules or unionfs-modules before you install remastersys.  On initial testing from a net-inst lenny cd I had not installed these prior and something very bad happened to my install - it was unable to boot and the livecd created was also unusable.  I feel it had something to do with building the initramfs.  As another safeguard, its recommended to reboot your system after the modules are installed just to ensure it boots properly.  If all that goes well, you are fully prepared to install and run remastersys for debian.
> 
>   If your kernel doesn't have the squashfs-modules and either the aufs-modules or unionfs-modules, you MUST use a different kernel.  No ifs ands or buts about it.

I also find confusing in how to run/install this, as the README.me does not mention it. The running commands on the original Remastersys were (at least in debian):  

> "remastersys backup" as root to make a full system backup,  or "remastersys dist" again as root, to make a distributable copy to share with friends. 

Should `remastersys` be run under `usr/bin` in [remastersys/usr/bin](https://github.com/nerun/remastersys/tree/main/remastersys/usr/bin)? Or rather be installed WITH this repo (and how)?

**Comment by nerun** [comment]
Hi thank you,

This is in ALPHA stage yet (v4.x.x). There's no debian package for it. The package in Releases is the 3.0.0 legacy version. Every time i test it in my machine i use the `package-creator` script. Packages has dependencies so if i install a deb package by `sudo apt install ./remastersys*.deb` it automatically installs all dependencies (must add `./`).

Dependencies list (from package-creator script):
`awk, bash, coreutils, dialog, fdisk, findutils, grub-pc, hwdata, laptop-detect, live-boot-initramfs-tools, live-boot, live-config-sysvinit | live-config-systemd, live-config, mkisofs | genisoimage, mount, os-prober, passwd, rsync, sed, squashfs-tools, sudo, syslinux | xorriso, syslinux-utils, util-linux, zstd`.

To install this `ALPHA` download the current source, use package-creator script in terminal to create debian packages, then install debian packages. But remember, it's an alpha, not a beta or a release candidate. It's /usr/bin, debian package install it in the right place.

To use it, just write remastersys in terminal, will appear a help message.

You should use sudo. So: `sudo remastersys backup`, `sudo remastersys dist` etc. Read usage help as explained.
