### ISSUE TITLE
Remastersys .iso > 4GB

### ISSUE THREAD

**Issue by lmaudio** [Nerun/remastersys#11]
I try to build an image in backup-mode with more than 4GB! Everything was fine during mastering but after all there is no .ISO and an error in the log about too large files over 4GB and missing parameters!

Could you help, please!?

Remastersys 4.8.1,  Linux Mint 21.1,  Mate,  64bit

**Comment by nerun** [comment]
Yes! Thank you for open this issue. Could you paste your log file here?

`/home/remastersys/remastersys.log`

Also, is `genisoimage` or `xorriso` installed?

**Comment by lmaudio** [comment]
Hi there! genisoimage is installed, xorriso NOT! Should i?
I used the remastersys-gui tool!

My logfile i deleted yesterday during reinstalling remastersys. i have the problem now that remastersys don t start - doesn t matter what i do, after i just closed the program without finishing the last backup-mode try. 
I hope to get this solved quickly to try another backup-mode and post you my logfile.
And thank you for your work developing and maintaining remastsys again.

**Comment by nerun** [comment]
Try to create a backup again. If still doesn't work then install xorriso and try again. If xorriso work i know what is the problem.

About Remastersys GUI not starting, try to open the GUI via terminal: `sudo remastersys --gui` (if work the problem should be `ysudo`). If fail again, use terminal/text version: `sudo remastersys backup`.

And show me the log!

**Comment by lmaudio** [comment]
Found this in net:

mkisofs -allow-limited-size -l -J -r -iso-level 3 -o <output.iso> <source file or directory>

genisoimage -allow-limited-size -l -J -r -iso-level 3 -o <output.iso> <source file or directory>

Either one of these commands will generate an ISO that is bigger than 4GB.

Remastersys starts again, so should i try one of this parameters!?

I will try now with xorisso and show you the log

**Comment by nerun** [comment]
`-iso-level 3 (or 4)` allow generate images larger than 4 GB. `-allow-limited-size` allow single files (the ones inside the image) larger than 4 GB.

Remastersys uses only `iso-level 4`. If you have files larger than 4 GiB then you should use `-allow-limited-size`. Since you are trying a backup, this can be the problem.

Other problem can be `grub-makerescue`. It is used instead of xorriso / genisoimage when boot option is GRUB (not ISOLINUX). Since i jave changed default option to GRUB recently... Is `grub-common` installed?

**Comment by lmaudio** [comment]
Little confusion now, sorry: First run with remastersys was Liveboot using ISOLINUX the default setting, now it's after a debugging clean reinstall of remastetsys the GRUB liveboot the default setting! I switched also from remastersys 4.7.1 to 4.8.1 yesterday.
Which one do you recommend to remaster a Linux Mit 21.1 based distro!?

**Comment by nerun** [comment]
Use version 4.8. Both ISOLINUX and GRUB works fine. GRUB is the default now.

Now you have said version 4.7 was installed i know that the upgrade not always works as expected. So is better to purge previous versions before install the new one. Sorry foe this. But it's a BETA this things happens.

**Comment by lmaudio** [comment]
So there is no grub-common installed on my system. Should i?

Or better take ISOLINUX!? 

How to deal with the parameter 

-allow-limited-size

Should i just put it in the options for mksquashfs of remastersys settings!?

**Comment by nerun** [comment]
If you have files larger than 4GiB and wanna try `-allow-limited-size`, edit file `/bin/remastersys`, and add this option in line 562.

**Comment by nerun** [comment]
Yes, install grub-common OR change to ISOLINUX in the configuration. Both should work. I will add grub-common to dependencies in the future.

**Comment by nerun** [comment]
```shell
if [ "$ISOBOOT" = "GRUB" ]; then
        phrase1="$Creating $CUSTOMISO $In $WORKDIR $Using grub-mkrescue."
        echo -e "\n$phrase1"
        log_msg "$phrase1"
        grub-mkrescue -iso-level 4 \
        -o $WORKDIR/$CUSTOMISO $WORKDIR/ISOTMP/ 2>>$WORKDIR/remastersys.log 1>>$WORKDIR/remastersys.log
```
Change to:
```shell
if [ "$ISOBOOT" = "GRUB" ]; then
        phrase1="$Creating $CUSTOMISO $In $WORKDIR $Using grub-mkrescue."
        echo -e "\n$phrase1"
        log_msg "$phrase1"
        grub-mkrescue -iso-level 4 -allow-limited-size \
        -o $WORKDIR/$CUSTOMISO $WORKDIR/ISOTMP/ 2>>$WORKDIR/remastersys.log 1>>$WORKDIR/remastersys.log
```

**Comment by lmaudio** [comment]
BTW: While mastering a distro with lot of diverse changes we choosed the backup-mode and put all userdata in the skel folder, because old remastersys 3.x was not taking all our changes, bringing rje Linux Mit default designs and settings back.
I will test the distro-mode with your new remastersys and maybe its the solution!?

But first i have to deal with the 4GB limitation.

**Comment by nerun** [comment]
Backup mode doesn't need to copy settings to /etc/skel, since it's a backup anyway. But if you want to create a Live CD with some custom settings but not with your current users and personal files in it, then you should use Dist Mode and copy settings to /est/skel.

**Comment by lmaudio** [comment]
There are always no personal data and the userspace contains all settings.
Old remastersys 3 was not taking all settings in distromode in the past, so that we choosed this "trick" to get all settings working.

I think maybe it was not belonging to remastersys, as more with the Linux Mint installer, overwriting some things by default.!?

**Comment by lmaudio** [comment]
Anyway, i will try now all your good tips and advises and write you how it works. Thank you so much for helping!

**Comment by lmaudio** [comment]
One question more: our Linux Mint based distro works with a 2GB swapfile. In the past we used an partioned swap.

Could this be the reason for having a too big isofile!??

**Comment by nerun** [comment]
Yes.

**Comment by nerun** [comment]
For the record: i have tried `-allow-limited-size` and it just works with `genisoimage`. Xorriso uses `xorrisofs` that is a short of `xorriso -as genisofs` that is an emulation mode to genisoimage. But xorrisofs do not support `-allow-limited-size`. Xorrisofs is used with ISOLINUX. And GRUB uses `grub-mkrescue` is a short for `xorrisofs`. I have started working in a fix for this issue too.

**Comment by lmaudio** [comment]
So what recommend you now if i want to remaster with grub as liveboot and without xorrisof installed? Have i just to write this line in grub, like you wrote above?

I will try now with a swap partition instead of a swapfile under Linux Mint.
If this don't work i will write a line with the allow-limited-size in grub.

If this don't works i will install xorrisof but it would be great to know what is the right entry in the remastersys-gui-settings for mksquashfs (or should i leave this like default??)

**Comment by nerun** [comment]
You can wait for version 4.9 or...

We don't really know what is your problem. This the point. YOU should test all above options. I don't know if your system (to be backuped) have files larger than 4 GB (but you should know). If not, you don't need `-allow-limited-size`. So, there's no problem. Just install `grub-common` and keep using GRUB as bootloader.

But if you have files larger than 4GB inside your system, you will need `-allow-limited-size`. Edit remastersys line 562 as i have suggested above _will not_ help you, since GRUB uses `grub-mkrescue` that uses `xorrisofs` that do not support `-allow-limited-size`. So young padawan your last hope is to use ISOLINUX (change it in settings) and **don't** install `xorriso`. If it's installed, purge it. It will force remastersys 4.8 to use `genisoimage`, that supports `-allow-limited-size`. But you will need to edit another line:

**Line 575**:
```shell
-iso-level 4 \
```
Change to:
```shell
-iso-level 4 -allow-limited-size \
```
And forget line 562...

**Comment by lmaudio** [comment]
Yea so great Master YODA! :)

I will check all this out and will report you.

As we build a distro for multimedia it is full with apps, Plugins and much more. Is possible that the image is over 4Gb..

I am using remastersys/penguy-builder many years and it is always a great adventure to rebuild  a stable system. Thanks for support!!

**Comment by nerun** [comment]
Just one note: there can be two different situations, alone or together:
- ISO image is larger than 4 GB >> it's fixed with `-iso-level 3` or 4
- One or more files are larger than 4 GB >> it's fixed with `-allow-limited-size`

**Comment by lmaudio** [comment]
CP: cannot stat  'etc/remastersys/isolinux/memtest86.bin': no such file or directory  ,same with memtest86+x64.bin and grub.cfg 

Error message in the beginning of the remasteringprocess in backup mode with remastersys-gui i can ignore?

I purged and deleting everything that depends to remastersys in /etc, before reinstalling and starting remastersys again.

This i had to do 2x because nothing happens when i was clicking the gui-icon, while after this i am able to start remastersys.

Seems that the gui-version is not really stable. 
But maybe now it will work for me!?

I will report you which method bringing success for me. 

And/or give the commandline-version a try..

**Comment by nerun** [comment]
GUI is stable (in a clean install). It's just a frontend to terminal scripts (/bin/remastersys most of time). Most of the problems occurs in remastersys package. My bad, BETA version change many things deep from one version to another and sometimes files are not properly updated when a new version is installed over old one.

**Comment by lmaudio** [comment]
I remember that penguy builder was deleting old profiles in initramfs/penguybuilder-firstboot !?

First try with Grub livebootmodus without any parameters set failed because i forgot to installiert xorisso. It was coming as an error message at the and of the log.

I try now with GRUB and xorriso and than with ISOLINUX without xorriso and the limits-parameter.

But first i have to repair the not starting of the GUI after backup mode.

**Comment by lmaudio** [comment]
I use sudo autoremove remastersys and deleting all remastersys files in /etc and reinstall it again to bring the GUI back. Wrong way?

**Comment by nerun** [comment]
No, your system should be a mess because of beta versions mess. Complete uninstall is good.
```shell
sudo apt purge remastersys remastersys-gui
sudo apt autopurge
sudo apt autoremove
sudo apt autoclean
sudo apt clean
sudo rm -f /bin/remastersys* /bin/ysudo
sudo rm -rf /etc/remastersys
sudo rm -f /etc/remastersys.conf
sudo rm -rf /lib/remastersys
sudo rm -rf /usr/share/doc/remastersys
sudo rm -rf /usr/share/doc/remastersys-gui
sudo rm -f /usr/share/menu/remastersys
sudo rm -f /usr/share/applications/remastersys*
```
This is the most important.

**Comment by lmaudio** [comment]
Yea great, thank's. I start a clean remastering now with remastersys 4.8.1-gui in Backupmode, GRUB as default liveboot and xorriso installed by myself!

Feels good and the GUI more stable as before.
I think there is no single file over 4GB and with xorriso maybe it works now, if the ISO is going larger.

I will report you. Wish me luck

Maybe it would be great to offer other people this little documentation how to get a clean install over previcious versions of remastersys.

Always your support here is awesome amazing.
I think remastersys is in good hands. Nice!

A beta tester :)

**Comment by lmaudio** [comment]
Yess! Just a clean reinstall of remastersys, switching from swapfile to a swap-partition and the install of xorriso was ending without errors during remastering and now i have a 6,6GB isofile image to test. Great.

Which program do you recommend to burn it on a pendrive?

**Comment by nerun** [comment]
Good!

There are many.  Linux Mint has one added by default too. I like 2 the most: [balena etcher](https://github.com/balena-io/etcher) and [ventoy](https://github.com/ventoy/Ventoy). Ventoy is the best!

**Comment by lmaudio** [comment]
ubiquity-frontend-gtk installer icon is not on the desktop on livesystem, while the livesystem OS booting well. I will test the installer. Should i put the installer by myself on desktop!?

**Comment by nerun** [comment]
Never used Ubuntu before. I have no idea. And, technically, this version of Remastersys is being developed to DEBIAN only, and not for its derivatives.

But I do give one recommendation: Remastersys is good for creating distros/backups from installed systems.  It is not useful to customize Live CD with existing installers, also because Remastersys has its own installer.  To do this, try [CUBIC](https://launchpad.net/cubic) .

I was able to create a custom Linux Mint installation media (with calamares installer) using CUBIC. It's looks easy and is stable. Remastersys is still beta (unstable) and with many bugs.

**Comment by nerun** [comment]
About icons in desktop. Remastersys put an icon to Remastersys Installer in Dektop too, but for some reason it never appears. I don't know how to fix this that's why i can't help.

EDIT: i have an idea, try to put icon in /etc/skel.

**Comment by lmaudio** [comment]
Yea thanks! But if i put it in skel it will be shown on desktop if i have installed the system too? 

In the last remastersys was deleting it after install. But in some versions or for some reasons it was not working everytime and seems to be an old Problem.

But i wonder that you wonder about the way i use ubiquity-installer and slideshow, because these are the standard installer in livesystems of Linux MINT and ubuntu. The ubiquity-gtk is just the grafical frontend.
We use a customize ubiquity-slideshow for our distro. And it works well, yesterday i was installing first time frome the succesful remastered system!

Also we have to do little changes and remaster again so it would be great about more to know about your way to create a livestem to install.

BTW: we are using Linux Mit 21.1, MATE DE

**Comment by lmaudio** [comment]
Linux Mint depends on Ubuntu, Ubuntu on Debian, so remastersys is not far away from that..

Is there a remastersys-fork for Linux Mint too?

Also, your remastersys works with my Linux Mint 21.1 and we made 3 images of Linux Mint with old remastersys in the past.

**Comment by lmaudio** [comment]
Cubic looks good. I will give it a try. Thank's! 

i think remastersys is more than a backup tool. E.g.to make a distro and livesystem to install. If i just need backup i will use clonezilla or the Linux Mint backup tool.

Your remastersys seems to be really stable and doing a good job. Don t be shy.

**Comment by nerun** [comment]
Thank you. Closing issue as resolved.
