### ISSUE TITLE
Not all files copied in /etc/remastersys - 4.9

### ISSUE THREAD

**Issue by lmaudio** [Nerun/remastersys#13]
I noticed that not all files copied in /etc/remastersys -  version4.9!

E.g. grub.cfg and others.

Triggers remastersys to give error messages and ends in a broken liveimage!?

Is this just on my machine or on others too?

**Comment by nerun** [comment]
> I noticed that not all files copied in /etc/remastersys - version4.9!
>
> E.g. grub.cfg and others.

Some files in `/etc/remastersys` are used by ISOLINUX (`/etc/remastersys/isolinux`) not GRUB (`/etc/remastersys/grub`). They will not be copied if ISOLINUX is not choosed. And GRUB is now the default option in Settings. Grub.cfg is used, but is not copied as it is. Many other files are help files, settings etc.

> Triggers remastersys to give error messages and ends in a broken liveimage!?

This phrase is confused to me. Sorry for this. What are you trying to say?

> Is this just on my machine or on others too?

What system are you using? Linux Mint? All my tests run in a Debian 11.6 system. I know that they are very close, but the true is that Ubunto/Mint are not Debian in fact.

I need more details to help you. Please, be more precise.

**Comment by lmaudio** [comment]
I just mean, that in remastersys Version 4.8 the grub.cfg and other important files were copied by default in /etc/remastersys-folder, while Version 4.9 did NOT after install.

This ends in an error message in remastersys while making a backup/distro-process.

I just followed your 14 commands to purge remastersys clearly, before installing a new Version of remastersys! 

Also maybe nice to here for you that we build our first stable beta distroimage with Version 4.8 that was working without errors!

**Comment by lmaudio** [comment]
BTW: is the ISOLINUX-Option compatible with (U)EFI !??

Other point:
I noticed that there are coming no xorriso-dependencies if i install Version 4.9 of remastersys and had xorriso NOT installed before. It is not longer needed in remastersys??

**Comment by lmaudio** [comment]
Edit: Problem solved:

After reinstall the whole system i noticed that remastersys 4.9 is copying grub and isolinux to etc/remastersys.

So the error was in my side!
