### ISSUE TITLE
Remove 4 GB ISO limitation

### ISSUE THREAD

**Issue by ddemuro** [Nerun/remastersys#2]
I have a patch that I worked on to remove the 4 GB limit so you can build a pendrive bootable version. It's a lot more useful to revive the "Backup" option.

If you're interested I could submit a PR

**Comment by nerun** [comment]
@ddemuro hi!

Yes, i am interested! I am not working on it right now, but if you submit a PR i can study this in the future.

Thank you very much for your time.

**Comment by nerun** [comment]
For the record, from Remastersys old site: [The 4GB limit explained - not a remastersys limitation](https://web.archive.org/web/20130423105647/http://www.remastersys.com/)

**Comment by ddemuro** [comment]
Yeah, I had read it and I was able to get it sort of working. The part I'm currently working on is fixing the installer, my case is not so much as to "media" but pre-shipping installed packages with their configurations.
Right now I'm at work and I don't recall what distro modified remastersys to build their ISOs and they worked around both issues.

Now what I don't know and I'm going to check their code is if they fixed it by using a different installer / patching the installer.

I'll report back, I have a branch where I can make the ISO but I do have the installing portion of the problem now.

**Comment by nerun** [comment]
See issue #8.
