### ISSUE TITLE
Password Issue

### ISSUE THREAD

**Issue by xybytz** [Nerun/remastersys#20]
### Discussed in https://github.com/nerun/remastersys/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **mcjka** March 12, 2023</sup>
Hello, I am on Ubuntu 22.04.. When I load the iso in Vmware, it fails to load bluethooth, snap, and unmount the medium. I am not posting this as an issue because I think it is a Me-issue. I am using the CLI version, and typed the command "remastersys dist" to generate. </div>

Now, I got it to work. However, I do not know the password. On the VM  I made it on, the password is xyz (not actual password but a placeholder) but xyz  is not the password of the system. This is driving me nuts. I really want to see it working! Yes, it boots and this is the log: droptext.cc/w9tps

Trying to run the iso on my Mac using UTM (a VM system), because my other laptop does not have enough storage.

**Comment by lmaudio** [comment]
I think this just happened in livesystem and if you install it from pendrive, the system will use your given password!?

Got the same problem on booted livesystem and found the pw "live" is the right pw in livesystem. (!!!)

So, it's not a bug!? It's a feauture: it doesn't matter which pw you gave before remastering - for the users of the installmedium/livesystem is "live" the pw and later the individual given, own password. 
You just have to know..

**Comment by xybytz** [comment]
Ok, I will try this by doing it on a pen drive and on a VM. Thanks for the help, Imaudio!

**Comment by xybytz** [comment]
Yay, it Worked! Thanks!

**Comment by nerun** [comment]
Good to know.

When running any live media (backup or dist mode) from image or from pendrive user will be always "live" and password is always "live".

But once you install the media on your system, If live media is a backup then user and password will be the ones of the backuped system (user and password provided in installation is not used). If is a live media of a DIST(ribution) the user and password will be the ones provided in installation process.
