### ISSUE TITLE
Add EFI / UEFI boot support

### ISSUE THREAD

**Issue by ddemuro** [Nerun/remastersys#3]
I was working on patching remastersys to allow to boot EFI systems, I think this would fix the fact only MBR boot is possible last I checked, but I'm not sure if you fixed it already or are planning on doing so.

**Comment by nerun** [comment]
@ddemuro hi!

Yes, i have the intention. But I am not working on it right now. If you have some code ready in this way, please submit it. Remastersys is a very outdated tool and still needs a lot of work. 

Thank you very much for your time.

**Comment by sxueck** [comment]
watching

**Comment by nerun** [comment]
### I am closing this issue

I will keep only issue #10 because it have some valuable help and this one is just a request.
