### ISSUE TITLE
install 4.4_1 doesn't work

### ISSUE THREAD

**Issue by LeOS-GSI** [Nerun/remastersys#5]
please seeerror message:

leos@LeOS-Linux:~/Downloads$ sudo dpkg -i remastersys_4.4-1_all.deb
[sudo] Password for leos: 
dpkg-deb: error: archive "remastersys_4.4-1_all.deb" uses unknown compression for element "control.tar.zst", abort
dpkg: Error while processing archive remastersys_4.4-1_all.deb (--install):
 "dpkg-deb --control" subprocess returned error value 2
Errors occurred while editing
 remastersys_4.4-1_all.deb

**Comment by nerun** [comment]
Hmm... Package was created in Linux Mint, maybe it causes any problem. Previous packages were created in Debian. 

I was unable to reproduce this issue.

Please, try to install ZSTD to see what happens: `sudo aptitude install zstd`

**Comment by nerun** [comment]
I was unable to reproduce this issue.

**Comment by LeOS-GSI** [comment]
zstd was already istalled:
zstd is right the actual Version (1.4.8+dfsg-2.1).

**Comment by nerun** [comment]
Well... I have no idea what to do. I will let this issue open, maybe in the future we find a fix for this.

NOTE FOR MYSELF: PeppermintOS based on latest Devuan.

**Comment by LeOS-GSI** [comment]
Any idea why 4.3 not working as I have written in the closed post #4 ? I have made the requested changes, but with backup still  no login

 PeppermintOS based on latest Devuan. yes

**Comment by nerun** [comment]
> Any idea why 4.3 not working as I have written in the closed post #4 ? I have made the requested changes, but with backup still no login
> 
> PeppermintOS based on latest Devuan. yes

Replied in #4

**Comment by nerun** [comment]
About this issue 5, i have a suggestion for you. Please, try to create a package yourself.

1. Download source code. [[download link here](https://github.com/nerun/remastersys/archive/refs/heads/main.zip)]
2. Unzip.
3. Enter uzipped folder.
4. Open a terminal in it.
5. Use `./package-creator` and follow instructions.
6. When asked version write: `4.4-peppermint-1`, for example.
7. When asked to update changelog, say `n` to all. You will be asked 4 times.

Packages should appear in main folder.

**Comment by LeOS-GSI** [comment]
OK, after changing the permission of both folders from 700 to 755 I was able to create. And a to install both deb. now I will start over with new backup.iso

**Comment by LeOS-GSI** [comment]
errors when using the gui option for creating the /etc/skel defaults
[skel-error.txt](https://github.com/nerun/remastersys/files/10300200/skl-error.txt)

could that be the root cause ?

EDIT: I think that's the problem. That's why distro is working and backup not. with distro, no 'home' and skel is used

**Comment by nerun** [comment]
Maybe, i don't know if skel is really working. I have not tested it yet.

**Comment by LeOS-GSI** [comment]
OK, I have tried it on MX-Linux (Debian 11) and backup iso is not booting. Could you pls try the creation of backup.iso ? the dist option is working, but it will loose all my user setup. 

Thx in advance

**Comment by LeOS-GSI** [comment]
OK, I give up. I have tried LightDM, GDM3 and Gnome display manger. I'm never able to login with Backup-LiveCD. The 'dist' iso works fine, but the 'backup' not. 
I have it also tried with MXlinux (also a Debian distro) and it's also not working.

The 'dist' iso doesn't fit my needs, so I give up.

**Comment by nerun** [comment]
@LeOS-GSI please take a look at issue #6. Backup mode was fixed. Now working on LightDM doesn't login in backup mode.
